### ISSUE TITLE
Missing Translation menu item

### ISSUE THREAD

**Issue by ntsbstn** [statikbe/laravel-filament-chained-translation-manager#21]
Hey ! 

First of all, thanks for the good job on this package, really useful.
I've been using it on Filament v2 for a while, and I recently switched to Filament v3. 

I was glad to see that you updated your package to this new version. 
Therefore, even if the upgrade went smoothly, I don't have a Translation menu item in the filament menu.

As the doc says, "The Translation Manager is automatically added to the Filament menu."
I wonder what I did wrong? 

I updated via composer, my version of the package is :    "statikbe/laravel-filament-chained-translation-manager": "^3.0",
I'm using Laravel 10 / PHP 8.2

My AppServiceProvider
```
    public function boot()
    {
        FilamentTranslationManager::setLocales(['en', 'fr', 'nl', 'es', 'it']);
    }
``` 

My config file
```
    'enabled' => true,
    'access' => [
    'limited' => false,
    ],
```

The tailwind config file is properly updated in my custom filament theme.
I published views and translations stubs.

Do you have any idea on how to solve this or have experienced the same after upgrading from v2 to v3 ?
I'm clueless.

Thanks.

**Comment by sten** [comment]
We are also working on upgrading two projects to filament v3. I am seeing the same issue there.

@alexandersix Did you also experience this? Did you configure it as a plugin? Thanks!

I will try to figure out this week what is going wrong and update the documentation or implementation accordingly.

**Comment by sten** [comment]
@ntsbstn I updated the docs and renamed the plugin class to reflect it is the chained translation manager.

You need to register the plugin in a panel provider of filament v3.  See the docs:

> Finally, for Filament v3, add the plugin to your panel in your panel provider in the panel() function:
```php
class AdminPanelProvider extends PanelProvider
{
    public function panel(Panel $panel): Panel
    {
        return $panel
            // ...
            ->plugin(FilamentChainedTranslationManagerPlugin::make());
    }
}
```

There is a new release: https://github.com/statikbe/laravel-filament-chained-translation-manager/releases/tag/3.0.1

Hope that works for you!

**Comment by ntsbstn** [comment]
It works like a charm. 
Thanks, @sten !

**Comment by ntsbstn** [comment]
I've been in too much of a hurry to say that it works like a charm, I'm experiencing immediate reloading of the page once I click in a field to update or add a new translation.

It might be linked to my custom theme, but hard to say since the page reloads itself quite fast, I don't have the time to check on the console.

Is it only on my side?

**Comment by sten** [comment]
@ntsbstn There is a fix for this in release v3.0.2. Let me know if you still experience problems!

**Comment by ntsbstn** [comment]
@sten Unfortunately, it doesn't resolve the problem.
As I understand, you don't encounter such a behavior.

I'd love to help you fix this, but I don't know where to start looking. Any clue?

https://github.com/statikbe/laravel-filament-chained-translation-manager/assets/23659828/40e62d93-efab-40d4-afa5-81b9e035d23d

**Comment by sten** [comment]
@ntsbstn Are you on v3.0.2? For me it works. Can you check if the files in the vendor are the same as this PR?
https://github.com/statikbe/laravel-filament-chained-translation-manager/pull/22/files

**Comment by ntsbstn** [comment]
@sten Aaaaaaaalright, I get it.

Actually, republishing the views doesn't override the previous ones.
I was using the 3.0.2 with the views of the 3.0.1

Now it works properly. 
Thank you and @almontasser for the fix.
